manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: george-norton
      url-base: https://github.com/george-norton
    - name: AYM1607
      url-base: https://github.com/AYM1607
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-driver-pmw3360
      remote: george-norton
      revision: v0.3
    - name: zmk-driver-azoteq-iqs5xx
      remote: AYM1607
      revision: main
  self:
    path: config
